/* H2 Database */
/*
CREATE TABLE IF NOT EXISTS userOOOInput(
                             id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                             slack_user_id varchar(255),
                             slack_username varchar(255),
                             description varchar(255),
                             start_time TIMESTAMP(9),
                             end_time TIMESTAMP(9)
);
*/
/* PostgreSQL */
SET CLIENT_ENCODING TO 'UTF8';

CREATE TABLE IF NOT EXISTS userOOOInput(
                            id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            slack_user_id varchar(255),
                            slack_username varchar(255),
                            description varchar(255),
                            start_time TIMESTAMP(9),
                            end_time TIMESTAMP(9)
);